#!/usr/bin/env python3
"""Build static site from data/*.yaml. Only dependency: PyYAML.

Outputs per product:  site/<slug>.html  .txt  .json  check-<slug>.sh
Plus:                 site/index.html   site/style.css   site/all.json
"""
import json, html, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).parent
OUT = ROOT / "site"
SITE_NAME = "pullist"
TAGLINE = "Firewall openings needed to pull container images."
SITE_URL = "https://pullist.d0t.se"
REPO_URL = "https://github.com/daniie/pullist"

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} &middot; {site}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<header><a class="brand" href="index.html">{site}</a><span class="tagline">{tagline}</span></header>
<main>
{body}
</main>
<footer>Generated {today} &middot; data lives in plain YAML &middot; corrections welcome via <a href="{repo}">pull request</a></footer>
</body>
</html>"""


def esc(s):
    return html.escape(str(s), quote=True)


def load_products():
    products = []
    for f in sorted((ROOT / "data").glob("*.yaml")):
        p = yaml.safe_load(f.read_text())
        p["_file"] = f.name
        products.append(p)
    return sorted(products, key=lambda p: p["title"].lower())


def host_rows(p):
    rows = []
    for h in p["hosts"]:
        req = h.get("required", True)
        tag = '<span class="tag req">required</span>' if req else '<span class="tag opt">optional</span>'
        ports = " ".join(f'<span class="port">{pt}</span>' for pt in h.get("ports", [443]))
        rows.append(
            f'<tr><td class="host">{esc(h["host"])}</td>'
            f'<td>{ports}</td><td>{esc(h.get("purpose", ""))}</td><td>{tag}</td></tr>'
        )
    return "\n".join(rows)


def plain_list(p, required_only=False):
    hosts = [h["host"] for h in p["hosts"] if h.get("required", True) or not required_only]
    return "\n".join(hosts)


def check_script(p):
    lines = [
        "#!/usr/bin/env sh",
        f"# Connectivity check for {p['title']} - run from inside the restricted network.",
        f"# Generated by {SITE_NAME} on {datetime.date.today()}. Needs: curl.",
        "# Any HTTP status counts as reachable; we only test that TCP/TLS gets through.",
        "fail=0",
        "check() {",
        '  code=$(curl -sS -o /dev/null -w "%{http_code}" --connect-timeout 5 "https://$1/" 2>/dev/null)',
        "  rc=$?",
        '  if [ "$rc" -eq 0 ] || [ "$code" != "000" ]; then',
        '    printf "OK    %s\\n" "$1"',
        "  else",
        '    printf "FAIL  %s  (curl exit %s: 6=dns 7=refused 28=timeout 35=tls)\\n" "$1" "$rc"',
        "    fail=1",
        "  fi",
        "}",
    ]
    for h in p["hosts"]:
        target = h.get("test_host", h["host"])
        if "*" in target:
            lines.append(f'echo "SKIP  {h["host"]}  (wildcard - no test_host set in data file)"')
            continue
        comment = " # representative host for " + h["host"] if h.get("test_host") else ""
        lines.append(f"check {target}{comment}")
    lines += ["exit $fail", ""]
    return "\n".join(lines)


def product_page(p):
    notes = f'<h2>Notes</h2><p class="notes">{esc(p["notes"]).strip()}</p>' if p.get("notes") else ""
    sources = "".join(f'<li><a href="{esc(s)}">{esc(s)}</a></li>' for s in p.get("sources", []))
    slug = p["slug"]
    body = f"""
<h1>{esc(p["title"])}</h1>
<p class="desc">{esc(p.get("description", ""))}</p>
<table>
<thead><tr><th>Host</th><th>Ports</th><th>Purpose</th><th></th></tr></thead>
<tbody>{host_rows(p)}</tbody>
</table>
{notes}
<h2>Copy-paste</h2>
<p>Plain domain list: <a href="{slug}.txt">{slug}.txt</a> &middot;
JSON: <a href="{slug}.json">{slug}.json</a> &middot;
connectivity test: <a href="check-{slug}.sh">check-{slug}.sh</a></p>
<pre>{esc(plain_list(p))}</pre>
<h2>Verify from inside the network</h2>
<pre>curl -fsSL {SITE_URL}/check-{slug}.sh | sh</pre>
<h2>Sources</h2>
<ul>{sources}</ul>
<p class="meta">Last verified: {esc(p.get("last_verified", "unknown"))} &middot; data file: data/{esc(p["_file"])}</p>
"""
    return PAGE.format(title=esc(p["title"]), site=SITE_NAME, tagline=TAGLINE,
                       body=body, today=datetime.date.today(), repo=REPO_URL)


def index_page(products):
    items = "".join(
        f'<tr><td><a href="{p["slug"]}.html">{esc(p["title"])}</a></td>'
        f'<td>{len(p["hosts"])} hosts</td><td>{esc(p.get("description", ""))}</td></tr>'
        for p in products
    )
    body = f"""
<h1>Which firewall openings does an image pull need?</h1>
<p class="desc">Registries are never one hostname: auth lives on one domain, manifests on another,
and layer downloads redirect to a CDN nobody opened. This site lists all of them, per product,
with sources and a test script.</p>
<table>
<thead><tr><th>Product</th><th></th><th></th></tr></thead>
<tbody>{items}</tbody>
</table>
"""
    return PAGE.format(title="index", site=SITE_NAME, tagline=TAGLINE,
                       body=body, today=datetime.date.today(), repo=REPO_URL)


CSS = """
:root { --ink:#1c2025; --soft:#5b6470; --line:#d9dde2; --bg:#f7f8f9; --card:#ffffff;
        --ok:#0a6e46; --okbg:#e2f3ea; --opt:#6b7280; --optbg:#eef0f2; --accent:#0a6e46; }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
       font:16px/1.55 system-ui, sans-serif; }
header { display:flex; align-items:baseline; gap:.8rem; padding:1rem 1.5rem;
         border-bottom:2px solid var(--ink); background:var(--card); }
.brand { font-weight:700; font-size:1.15rem; color:var(--ink); text-decoration:none;
         font-family:ui-monospace, SFMono-Regular, Menlo, monospace; }
.brand::before { content:"> "; color:var(--accent); }
.tagline { color:var(--soft); font-size:.9rem; }
main { max-width:60rem; margin:0 auto; padding:1.5rem; }
h1 { font-size:1.5rem; margin:.5rem 0; }
h2 { font-size:1.05rem; margin-top:2rem; }
.desc { color:var(--soft); max-width:46rem; }
table { width:100%; border-collapse:collapse; background:var(--card);
        border:1px solid var(--line); font-size:.92rem; }
th { text-align:left; font-size:.75rem; text-transform:uppercase; letter-spacing:.05em;
     color:var(--soft); padding:.5rem .75rem; border-bottom:1px solid var(--line); }
td { padding:.5rem .75rem; border-bottom:1px solid var(--line); vertical-align:top; }
tr:last-child td { border-bottom:none; }
.host { font-family:ui-monospace, SFMono-Regular, Menlo, monospace; white-space:nowrap; }
.port { font-family:ui-monospace, monospace; font-size:.8rem; background:var(--optbg);
        padding:.05rem .35rem; border-radius:3px; }
.tag  { font-size:.72rem; text-transform:uppercase; letter-spacing:.04em;
        padding:.1rem .4rem; border-radius:3px; }
.tag.req { color:var(--ok); background:var(--okbg); }
.tag.opt { color:var(--opt); background:var(--optbg); }
pre { background:var(--card); border:1px solid var(--line); padding:.9rem 1rem;
      overflow-x:auto; font-size:.85rem; }
.notes { white-space:pre-line; background:var(--card); border-left:3px solid var(--accent);
         padding:.75rem 1rem; max-width:46rem; }
.meta { color:var(--soft); font-size:.85rem; }
footer { color:var(--soft); font-size:.82rem; text-align:center; padding:2rem 1rem; }
a { color:var(--accent); }
@media (max-width:600px){ .host{white-space:normal; word-break:break-all;} main{padding:1rem;} }
"""


def main():
    OUT.mkdir(exist_ok=True)
    products = load_products()
    (OUT / "style.css").write_text(CSS.strip() + "\n")
    (OUT / "index.html").write_text(index_page(products))
    for p in products:
        slug = p["slug"]
        (OUT / f"{slug}.html").write_text(product_page(p))
        (OUT / f"{slug}.txt").write_text(plain_list(p) + "\n")
        (OUT / f"check-{slug}.sh").write_text(check_script(p))
        (OUT / f"{slug}.json").write_text(json.dumps(
            {k: v for k, v in p.items() if not k.startswith("_")}, indent=2, default=str))
    (OUT / "all.json").write_text(json.dumps(
        [{k: v for k, v in p.items() if not k.startswith("_")} for p in products],
        indent=2, default=str))
    print(f"Built {len(products)} products -> {OUT}/")


if __name__ == "__main__":
    main()
